### ISSUE TITLE
Move nodes to docker network

### ISSUE THREAD

**Issue by MrHash** [NGUtech/bitcoin-stack#6]

**Comment by Lcote71** [comment]
How I can fix

**Comment by MrHash** [comment]
See https://docs.docker.com/compose/networking/#specify-custom-networks and examples in fork https://github.com/dkrm0/bitcoin-stack/commit/8cdc5b664ffa49f83d958f844a47999e9698aa7d & https://github.com/dkrm0/bitcoin-stack/commit/eea2c3b8778e64bfab479598891e22c4684931e2

**Comment by MrHash** [comment]
a50f346f8901802e2949468ff9e2d386ef716812
