### ISSUE TITLE
Error starting containers on Windows

### ISSUE THREAD

**Issue by dellagustin** [NGUtech/bitcoin-stack#7]
Hello, thanks for this great content.
I am testing it on a windows machine.

when running `docker-compose up -d bitcoin` I get the error `ERROR: .OSError: [Errno 22] Invalid argument: '.\\docker-compose.bitcoin.yml:docker-compose.elements.yml:docker-compose.yml'`.

After a brief analysis, I reached the conclusion that it is because the default separator for `COMPOSE_FILE` on windows is `;` instead of `:`.

I could solve it by adding to the `.env` file: `COMPOSE_PATH_SEPARATOR=:`

Reference: https://docs.docker.com/compose/reference/envvars/#compose_path_separator

**Comment by MrHash** [comment]
Yeah i believe you need to replace the `:` with `;` on windows as standard but that's a good fix i'll add it in. Do the containers build ok on windows? i don't have a windows machine so couldn't prebuild the images.

**Comment by dellagustin** [comment]
Thanks for the quick response, I did not try to build images, I am using the pre built ones.
